name: Android Build Pipeline
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: memory-master

      - name: Verify critical files
        run: |
          cd memory-master
          echo "=== Verifying required files ==="
          if [ ! -f "app.py" ]; then
            echo "::error::app.py is missing! Create this file first."
            exit 1
          fi
          [ -f "words.txt" ] || echo "::warning::words.txt is missing (optional)"
          [ -f "correct.wav" ] || echo "::warning::correct.wav is missing (optional)"
          [ -f "wrong.wav" ] || echo "::warning::wrong.wav is missing (optional)"
          echo "=== Found files ==="
          ls -la

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install system dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            openjdk-17-jdk \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            pkg-config \
            libgl1-mesa-dev \
            gradle

      - name: Prepare project structure
        run: |
          cd memory-master
          mkdir -p memorymaster
          mv app.py memorymaster/
          [ -f words.txt ] && mv words.txt memorymaster/
          [ -f correct.wav ] && mv correct.wav memorymaster/
          [ -f wrong.wav ] && mv wrong.wav memorymaster/
          echo "MIT License" > LICENSE
          echo "=== Project structure ==="
          tree || ls -R

      - name: Build Android APK
        run: |
          cd memory-master
          export SDL2_DIR=/usr/lib/x86_64-linux-gnu/cmake/SDL2
          briefcase create android
          briefcase build android
          mkdir -p dist
          cp android/*/outputs/apk/*/*.apk dist/

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: memory-master/dist/*.apk
          retention-days: 7

      - name: Archive logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: |
            memory-master/android/build/outputs/logs/*.log
            memory-master/android/gradle/wrapper/gradle-wrapper.properties
          retention-days: 3
