name: Build APK
on: [push, workflow_dispatch]  # Запуск при push и вручную

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y openjdk-17-jdk

      - name: Install Python packages
        run: |
          pip install briefcase toga-android pygame

      - name: Build Android APK
        run: |
         python -m pip install briefcase
         briefcase create android
         briefcase build android

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: android/gradlew/build/outputs/apk/debug/*.apk
