name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            openjdk-17-jdk \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            pkg-config \
            libgl1-mesa-dev

      - name: Clean Gradle cache
        run: |
          rm -rf ~/.gradle/caches

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install briefcase toga-android pygame

      - name: Build Android APK
        run: |
          export SDL2_DIR=/usr/lib/x86_64-linux-gnu/cmake/SDL2
          briefcase create android -v
          sed -i 's/gradle-8.2-bin.zip/gradle-7.6-bin.zip/g' memory-master/android/gradle/wrapper/gradle-wrapper.properties
          briefcase build android -v

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: |
            memory-master/android/**/outputs/apk/**/*.apk
            memory-master/android/**/outputs/bundle/**/*.aab