name: Build Android APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            openjdk-17-jdk \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            pkg-config \
            libgl1-mesa-dev

      - name: Clean Gradle cache
        run: |
          rm -rf ~/.gradle/caches

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install briefcase toga-android pygame

      - name: Create project structure
        run: |
          mkdir -p memorymaster
          [ -f app.py ] && mv app.py memorymaster/
          [ -f words.txt ] && mv words.txt memorymaster/
          [ -f correct.wav ] && mv correct.wav memorymaster/ || true
          [ -f wrong.wav ] && mv wrong.wav memorymaster/ || true
          echo "MIT License" > LICENSE

      - name: Build Android APK
        run: |
          export SDL2_DIR=/usr/lib/x86_64-linux-gnu/cmake/SDL2
          briefcase create android -v
          
          # Проверяем и обновляем версию Gradle
          if [ -f "android/gradle/wrapper/gradle-wrapper.properties" ]; then
            sed -i 's/gradle-8.2-bin.zip/gradle-7.6-bin.zip/g' android/gradle/wrapper/gradle-wrapper.properties
            echo "Gradle version updated to 7.6"
          else
            echo "gradle-wrapper.properties not found, using default version"
          fi
          
          briefcase build android -v

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: |
            android/**/outputs/apk/**/*.apk
            android/**/outputs/bundle/**/*.aab
          retention-days: 7