name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            openjdk-17-jdk \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            pkg-config \
            libgl1-mesa-dev
            
      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install briefcase toga-android pygame
          
      - name: Set up environment
        run: |
          echo "SDL_CFLAGS=$(sdl2-config --cflags)" >> $GITHUB_ENV
          echo "SDL_LIBS=$(sdl2-config --libs)" >> $GITHUB_ENV
          
      - name: Build Android APK
        run: |
          export SDL2_DIR=/usr/lib/x86_64-linux-gnu/cmake/SDL2
          briefcase create android -v
          briefcase build android -v
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: android/**/build/outputs/apk/**/*.apk
