name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: sudo apt update && sudo apt install -y openjdk-17-jdk
      - run: pip install briefcase toga-android pygame
      - run: |
          briefcase create android
          briefcase build android
      - uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: android/**/outputs/apk/**/*.apk
