name: Android Build
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install system dependencies
        run: |
          sudo apt update -y
          sudo apt install -y \
            openjdk-17-jdk \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            pkg-config \
            libgl1-mesa-dev \
            gradle-7.6

      - name: Clean environment
        run: |
          rm -rf ~/.gradle/
          rm -rf ~/.cache/pip/
          rm -rf __pycache__/
          rm -rf .pytest_cache/

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip wheel
          pip install briefcase toga-android pygame==2.6.0

      - name: Prepare project structure
        run: |
          echo "=== PREPARING PROJECT STRUCTURE ==="
          mkdir -p memorymaster
          
          # Move files safely
          if [ -f "app.py" ]; then
            mv app.py memorymaster/
            echo "Moved app.py to memorymaster/"
          else
            echo "app.py not found!"
            exit 1
          fi
          
          if [ -f "words.txt" ]; then
            mv words.txt memorymaster/
            echo "Moved words.txt to memorymaster/"
          else
            echo "words.txt not found!"
            exit 1
          fi
          
          echo "MIT License" > LICENSE
          echo "=== PROJECT STRUCTURE ==="
          ls -lR

      - name: Build Android APK
        run: |
          echo "=== STARTING BUILD ==="
          export GRADLE_OPTS="-Dorg.gradle.daemon=false"
          
          # Clean previous builds
          rm -rf android/ build/ dist/
          
          # Create project
          briefcase create android -v
          
          # Force Gradle 7.6
          cd android
          ./gradlew wrapper --gradle-version 7.6
          cd ..
          
          # Build project
          briefcase build android -v
          
          echo "=== BUILD OUTPUT ==="
          find android -name "*.apk" -o -name "*.aab" | while read f; do
            echo "Found: $f"
          done

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: |
            android/**/outputs/apk/**/*.apk
            android/**/outputs/bundle/**/*.aab
          retention-days: 7
